### ISSUE TITLE
Resending verify account link when `verify_account_grace_period` feature enabled

### ISSUE THREAD

**Issue by 1gor** [jeremyevans/rodauth#30] opened 2017-03-10 08:11 UTC
Usecase: user has lost his initial verify account email and needs to request it again using  `resend_verify_account_view` (form with "Send verification again" button). 

Problem: There is no way for him to request new verification email. 

The issues arise for me with the following features are enabled: `verify_account_grace_period` combined with `verify_change_login`, `verify_change_password` and `reset_password`.

The `verify_account` feature provides only two methods to display the "Send verification again" form:
-  the `new_account`
- `before_login_attempt`

In my situation `before_login_attempt` method does not let the user to re-request verification code, because when user tries to use the correct password, he simply is logged in. When he ises an incorrect password, a 'reset password' feature is triggered. 

So he is left with a rather counter-intuitive method of trying to create an account with the same login to see the 'Send verification again' form.

Here the form submission fails which I think is a bug. In `verify_account.rb` feature the `open_account?` always evaluates to `true` (due to original method from `base.rb` being overwritten by `verify_account_grace_period` feature). So in `verify_account_resent` route email is never sent (and it displays the error message).

The following code change fixes the problem it seems (`features/verify_account.rb`):

``` ruby
 route(:verify_account_resend) do |r|
      verify_account_check_already_logged_in
      before_verify_account_resend_route

      r.post do
        # if account_from_login(param(login_param)) && !open_account?
        if account_from_login(param(login_param)) && account[account_status_column] == account_unverified_status_value 
/.../
      end
 end

```

Apart from the perceived bug, the genral issue remains. The user needs to have a simple and intuitive way to re-send himself a 'verify account' link. There is no separate view for that. (It can easily be added as a plugin configuration, of course, but I think it should be in as a default).

**General comment**

I see `rodauth` using `response.write` in various places (features) to display such forms (password reset, for example). Is this really necessary? Maybe it is better to provide a separate view with a form in each case? 

For example, in case of forgotten password, users generally expect to see a 'remind password' link on a login form leading to a separate view. They do not expect to be offered a password reminder form *after* they have tried a wrong password. They reason something like this: "I see a login form, but I don't remember my password. Where is that 'forgot password' link?"

**Comment by jeremyevans** [comment] 2017-03-10 16:24
OK, it looks like there are multiple issues here.

First, verify_account not sending the verify account link in verify_account_resend if verify_account_grace_period is used.  I agree this should be fixed, though I'll probably want to add a separate method for the check instead of hard coding the logic in the route.

Second, providing the user a way to request the verify account link without trying to create a new account with the same login.  I'm guessing this would be a page with a single button that just sends the verify account email.  It would only be available for logged in, unverified accounts, and would be part of the verify_account_grace_period feature.

Third, providing the user a way to request a password reset without a login attempt.  This is probably doable via handling GET requests in reset_password_request and showing a forum that takes a login, and then showing a link to that page in the login form, similar to where the create_account link is shown.

Fourth, the use of `response.write`.  I'm not sure I understand what the problem is here, as there are already separate methods (`resend_verify_account_view` and `unlock_account_request_view`) that the developer can override if they want to customize the output.  `response.write` followed by `request.halt` is just a way to return the view to the user, it's the same as what happens internally if a route block returns a string.  So I don't think anything needs to be fixed here.

I'll work on the first three issues and should have them implemented before the next release.

**Comment by jeremyevans** [comment] 2017-03-10 20:59
Commits between 2a69fb67469af1af0fe31c5b65bb673c01cf274c and ed4fdc7234e0d96760e070f9975278b941654c74 should fix the three issues.  If you think there is an issue with any of them, please let me know.

**Closed by jeremyevans** 2017-03-10 20:59 UTC
